// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVSoxpD4JcZLfCB_IU7UHAi0S8q71bKwg',
    appId: '1:655579466965:web:59f08ba324c51a34ffe65c',
    messagingSenderId: '655579466965',
    projectId: 'my-ecommerce-app-0101',
    authDomain: 'my-ecommerce-app-0101.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-0101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKsdfdYTxwkxs8Wfwg1FE0ZArgSroRknA',
    appId: '1:655579466965:android:cb073fb51fd2b997ffe65c',
    messagingSenderId: '655579466965',
    projectId: 'my-ecommerce-app-0101',
    storageBucket: 'my-ecommerce-app-0101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnxyShRe_gSbAuwcehugUrZR8tCuPek7s',
    appId: '1:655579466965:ios:3cacb0447d7ff941ffe65c',
    messagingSenderId: '655579466965',
    projectId: 'my-ecommerce-app-0101',
    storageBucket: 'my-ecommerce-app-0101.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnxyShRe_gSbAuwcehugUrZR8tCuPek7s',
    appId: '1:655579466965:ios:3cacb0447d7ff941ffe65c',
    messagingSenderId: '655579466965',
    projectId: 'my-ecommerce-app-0101',
    storageBucket: 'my-ecommerce-app-0101.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVSoxpD4JcZLfCB_IU7UHAi0S8q71bKwg',
    appId: '1:655579466965:web:f209bd87c63af7bfffe65c',
    messagingSenderId: '655579466965',
    projectId: 'my-ecommerce-app-0101',
    authDomain: 'my-ecommerce-app-0101.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-0101.firebasestorage.app',
  );
}
